name: Tastings CI

on:
  push:
    branches:
      - "main"
      - "v*.*.*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2

      - run: mv mix.exs mix.exs.ignore

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "24.2"
          elixir-version: "1.13.1"
          gleam-version: "0.19.0"

      - run: mix archive.install hex mix_gleam --force
      - run: mv mix.exs.ignore mix.exs
      - run: mix deps.get
      - uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - run: gleam format --check src test
      - run: mix gleam.test
      - run: mix test

  # deploy:
  #   needs: build # Will only run if the test job succeeds
  #   if: github.ref == 'refs/heads/main' # Only run this job if it is on the main branch
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         ref: main # Check out main instead of the latest commit
  #         fetch-depth: 0 # Checkout the whole branch
  #     - uses: actions/setup-python@v2
  #       with:
  #         python-version: 3.8.1
  #     - uses: mhanberg/gigalixir-action@v0.6.1
  #       with:
  #         GIGALIXIR_USERNAME: ${{ secrets.GIGALIXIR_USERNAME }}
  #         GIGALIXIR_PASSWORD: ${{ secrets.GIGALIXIR_PASSWORD }}
  #         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  #         GIGALIXIR_APP: tastings # Feel free to also put this in your secrets
  #         MIGRATIONS: false # defaults to true
